config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  
  get 'tweets' => 'tweets#index'

  
  get 'tweet/:id' =>'tweets#show', as: 'tweet'

  get 'tweets/new', as: 'new_tweet'

  get 'tweets/edit'
  
  get 'tweets/:id/edit' => 'tweets#edit', as: 'edit_tweet'

  post 'tweets' => 'tweets#create'
  
  patch 'tweet/:id' => 'tweets#update'
  
  delete 'tweet/:id' => 'tweets#destroy', as: 'destroy_tweet'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
  #before_action :configure_permitted_parameters, if: :devise_controller?
  
  #protected

  #def configure_permitted_parameters
  #  devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :location, :bio])
  #  devise_parameter_sanitizer.permit(:account_update, keys: [:username, :location, :bio])
  #end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
      @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end
  
  def create
      @tweet = Tweet.new(tweet_params)
      
      if @tweet.save 
          redirect_to @tweet, notice: "tweet was successfuly create"
        else
        render :new
      end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

def update
  @tweet = Tweet.find(params[:id])
  @tweet.update(tweet_params)
  if @tweet.save
    redirect_to @tweet, notice: "tweet update"
  else
    render :edit, notice: "tweet could not be update"
  end
end


def destroy
  @tweet = Tweet.find(params[:id])
  @tweet.destroy
  redirect_to root_path
end


private
  def tweet_params
    params.require(:tweet).permit(:name, :message)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

<%= form_for(@tweet) do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :message %>
	<%= f.text_area :message %>
	
	<%= f.submit %>
	
	<%= link_to 'Delete', tweet_path(@tweet), method: delete %>
			
<% end %>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

<%= render 'form' %>

app/views/tweets/index.html.erb
<!-- Latest compiled and minified CSS -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

<!-- Optional theme -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">-->

<!-- Latest compiled and minified JavaScript -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->



<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">

<div class="container-fluid">
    <h1>Tweets#index</h1>
    <p>Find me in app/views/tweets/index.html.erb</p>
    <%= link_to 'New Tweet', new_tweet_path %>
    
    <%= @tweets.each do |tweet|%>
        <h3><%=tweet.name %></h3>
        <p><%=tweet.message%></p>
        <p><%= link_to 'Show Tweet', tweet%></p>
    <% end %>
</div>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>


<%= form_for(@tweet) do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :message %>
	<%= f.text_area :message %>
	
	<%= f.submit %>
		
<% end %>

app/views/tweets/show.html.erb
<%= notice %>

<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>


<h3><%= @tweet.name %> Said:</h3>
<p><%= @tweet.message %></p>
<p><%=@tweet.id%></p>

<%= link_to "Back", root_path %>

<%= link_to "Edit", edit_tweet_path(id: @tweet.id)%>